"""add description to workspace

Revision ID: 2447409340d1
Revises: 6911bb9df7df
Create Date: 2026-07-30 22:32:04.923135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2447409340d1'
down_revision: Union[str, Sequence[str], None] = '6911bb9df7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('workspace_id', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.drop_index(op.f('name'), table_name='projects')
    op.create_unique_constraint('uq_project_name_in_workspace', 'projects', ['name', 'workspace_id'])
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspace_id'], ['id'])
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('workspaces', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'workspaces', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='unique')
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'description')
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint('uq_project_name_in_workspace', 'projects', type_='unique')
    op.create_index(op.f('name'), 'projects', ['name'], unique=True)
    op.drop_column('projects', 'is_archived')
    op.drop_column('projects', 'workspace_id')
    # ### end Alembic commands ###
