"""Consolidate creator fields in Task model

Revision ID: f40960ae25d0
Revises: 2447409340d1
Create Date: 2026-08-03 16:58:57.505018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f40960ae25d0'
down_revision: Union[str, Sequence[str], None] = '2447409340d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'status',
               existing_type=mysql.ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE'),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               existing_nullable=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.drop_constraint(op.f('tasks_ibfk_3'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    op.drop_column('tasks', 'reporter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reporter_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_ibfk_3'), 'tasks', 'users', ['reporter_id'], ['id'])
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               type_=mysql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT'),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               type_=mysql.ENUM('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE'),
               existing_nullable=False)
    op.drop_column('tasks', 'creator_id')
    # ### end Alembic commands ###
